version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm i
      - cd apps/ionic-reserb/ && npm i
  build:
    commands:
      - npm run build.ionic.reserb
artifacts:
  files:
    - '**/*'
